/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import database.Database;
import javax.swing.JOptionPane;
/**
 *
 * @author USER
 */
public class FormPurchase extends javax.swing.JFrame {
    private static int grandTotalDefault = 0;
    /**
     * Creates new form FormPurchase
     */
    public FormPurchase() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtGrandTotal = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPurchase_ID = new javax.swing.JTextField();
        txtVendor_ID = new javax.swing.JTextField();
        txtVendor_RefNo = new javax.swing.JTextField();
        buttonView = new javax.swing.JButton();
        txtViewVendor_Name = new javax.swing.JTextField();
        txtPurchase_Date = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtProduct_ID1 = new javax.swing.JTextField();
        txtProduct_ID2 = new javax.swing.JTextField();
        txtProduct_ID3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtProduct_Name1 = new javax.swing.JTextField();
        txtProduct_Name2 = new javax.swing.JTextField();
        txtProduct_Name3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtQty1 = new javax.swing.JTextField();
        txtQty2 = new javax.swing.JTextField();
        txtQty3 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtPrice1 = new javax.swing.JTextField();
        txtPrice2 = new javax.swing.JTextField();
        txtPrice3 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtSubTotal1 = new javax.swing.JTextField();
        txtSubTotal2 = new javax.swing.JTextField();
        txtSubTotal3 = new javax.swing.JTextField();
        buttonSimpan = new javax.swing.JButton();
        buttonKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Pembelian");

        jPanel4.setBackground(new java.awt.Color(255, 255, 102));

        txtGrandTotal.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        txtGrandTotal.setText("Rp0,-");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtGrandTotal)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtGrandTotal)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(556, 556, 556)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(410, 410, 410)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Purchase ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Tanggal");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Kode Vendor");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Vendor Ref No");

        txtPurchase_ID.setBackground(new java.awt.Color(255, 255, 0));

        txtVendor_ID.setBackground(new java.awt.Color(255, 255, 0));

        txtVendor_RefNo.setBackground(new java.awt.Color(255, 255, 0));

        buttonView.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        buttonView.setText("View");
        buttonView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonViewActionPerformed(evt);
            }
        });

        txtViewVendor_Name.setEditable(false);
        txtViewVendor_Name.setBackground(new java.awt.Color(255, 255, 0));

        txtPurchase_Date.setBackground(new java.awt.Color(255, 255, 0));
        txtPurchase_Date.setForeground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPurchase_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPurchase_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtVendor_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)
                                .addComponent(buttonView)
                                .addGap(18, 18, 18)
                                .addComponent(txtViewVendor_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtVendor_RefNo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPurchase_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtPurchase_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtVendor_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonView)
                    .addComponent(txtViewVendor_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtVendor_RefNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Purchase Detail");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("Product ID 1");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Product ID 2");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("Product ID 3");

        txtProduct_ID1.setBackground(new java.awt.Color(255, 255, 0));
        txtProduct_ID1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtProduct_ID1CaretUpdate(evt);
            }
        });

        txtProduct_ID2.setBackground(new java.awt.Color(255, 255, 0));
        txtProduct_ID2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtProduct_ID2CaretUpdate(evt);
            }
        });

        txtProduct_ID3.setBackground(new java.awt.Color(255, 255, 0));
        txtProduct_ID3.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtProduct_ID3CaretUpdate(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setText("Nama Product 1");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setText("Nama Product 2");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setText("Nama Product 3");

        txtProduct_Name1.setEditable(false);
        txtProduct_Name1.setBackground(new java.awt.Color(255, 255, 0));

        txtProduct_Name2.setEditable(false);
        txtProduct_Name2.setBackground(new java.awt.Color(255, 255, 0));
        txtProduct_Name2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtProduct_Name2CaretUpdate(evt);
            }
        });

        txtProduct_Name3.setEditable(false);
        txtProduct_Name3.setBackground(new java.awt.Color(255, 255, 0));
        txtProduct_Name3.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtProduct_Name3CaretUpdate(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel13.setText("Quantity 1");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel14.setText("Quantity 2");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel15.setText("Quantity 3");

        txtQty1.setBackground(new java.awt.Color(255, 255, 0));
        txtQty1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtQty1CaretUpdate(evt);
            }
        });

        txtQty2.setBackground(new java.awt.Color(255, 255, 0));
        txtQty2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtQty2CaretUpdate(evt);
            }
        });

        txtQty3.setBackground(new java.awt.Color(255, 255, 0));
        txtQty3.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtQty3CaretUpdate(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel16.setText("Price 1");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel17.setText("Price 2");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel18.setText("Price 3");

        txtPrice1.setBackground(new java.awt.Color(255, 255, 0));
        txtPrice1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtPrice1CaretUpdate(evt);
            }
        });

        txtPrice2.setBackground(new java.awt.Color(255, 255, 0));
        txtPrice2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtPrice2CaretUpdate(evt);
            }
        });

        txtPrice3.setBackground(new java.awt.Color(255, 255, 0));
        txtPrice3.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtPrice3CaretUpdate(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel19.setText("Sub Total 1");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel20.setText("Sub Total 2");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel21.setText("Sub Total 3");

        txtSubTotal1.setEditable(false);
        txtSubTotal1.setBackground(new java.awt.Color(255, 255, 0));
        txtSubTotal1.setText("0");

        txtSubTotal2.setEditable(false);
        txtSubTotal2.setBackground(new java.awt.Color(255, 255, 0));
        txtSubTotal2.setText("0");

        txtSubTotal3.setEditable(false);
        txtSubTotal3.setBackground(new java.awt.Color(255, 255, 0));
        txtSubTotal3.setText("0");

        buttonSimpan.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        buttonSimpan.setText("Simpan");
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });

        buttonKeluar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        buttonKeluar.setText("Keluar");
        buttonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(txtProduct_ID1)
                    .addComponent(txtProduct_ID2)
                    .addComponent(txtProduct_ID3))
                .addGap(70, 70, 70)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11)
                        .addComponent(jLabel12))
                    .addComponent(txtProduct_Name1)
                    .addComponent(txtProduct_Name2)
                    .addComponent(txtProduct_Name3, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                .addGap(57, 57, 57)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addComponent(txtQty1)
                        .addComponent(txtQty2)
                        .addComponent(txtQty3, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)))
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18)
                    .addComponent(txtPrice1)
                    .addComponent(txtPrice2)
                    .addComponent(txtPrice3, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(txtSubTotal1)
                    .addComponent(txtSubTotal2)
                    .addComponent(txtSubTotal3, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16)
                    .addComponent(jLabel19))
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProduct_ID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProduct_Name1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQty1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSubTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14)
                    .addComponent(jLabel17)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProduct_ID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProduct_Name2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQty2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrice2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSubTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSimpan))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12)
                    .addComponent(jLabel15)
                    .addComponent(jLabel18)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProduct_ID3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProduct_Name3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQty3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrice3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSubTotal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonKeluar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonViewActionPerformed
        try{
            Connection connection = Database.koneksiKeDatabase();
            Statement statement = connection.createStatement();
            String query = "SELECT vendor_name FROM vendor WHERE vendor_id = " + this.txtVendor_ID.getText();
            ResultSet result = statement.executeQuery(query);
            while(result.next()){
                this.txtViewVendor_Name.setText(result.getString("vendor_name"));
            }
            result.close();
            statement.close();
        }catch(SQLException error){
            JOptionPane.showMessageDialog(null, "Maaf terjadi error: " + error);
        }
    }//GEN-LAST:event_buttonViewActionPerformed

    private void txtProduct_ID1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtProduct_ID1CaretUpdate
        try{
            Connection connection = Database.koneksiKeDatabase();
            Statement statement = connection.createStatement();
            String query = "SELECT product_name FROM product WHERE product_id = " + this.txtProduct_ID1.getText();
            ResultSet result = statement.executeQuery(query);
            while(result.next()){
                this.txtProduct_Name1.setText(result.getString("product_name"));
            }
            result.close();
            statement.close();
        }catch(SQLException error){
            JOptionPane.showMessageDialog(null, "Terjadi error: " + error);
        }
    }//GEN-LAST:event_txtProduct_ID1CaretUpdate

    private void txtProduct_Name2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtProduct_Name2CaretUpdate
        
    }//GEN-LAST:event_txtProduct_Name2CaretUpdate

    private void txtProduct_Name3CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtProduct_Name3CaretUpdate

    }//GEN-LAST:event_txtProduct_Name3CaretUpdate

    private void txtProduct_ID2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtProduct_ID2CaretUpdate
        try{
            Connection connection = Database.koneksiKeDatabase();
            Statement statement = connection.createStatement();
            String query = "SELECT product_name FROM product WHERE product_id = " + this.txtProduct_ID2.getText();
            ResultSet result = statement.executeQuery(query);
            while(result.next()){
                this.txtProduct_Name2.setText(result.getString("product_name"));
            }
            result.close();
            statement.close();
        }catch(SQLException error){
            JOptionPane.showMessageDialog(null, "Terjadi error: " + error);
        }
    }//GEN-LAST:event_txtProduct_ID2CaretUpdate

    private void txtProduct_ID3CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtProduct_ID3CaretUpdate
        try{
            Connection connection = Database.koneksiKeDatabase();
            Statement statement = connection.createStatement();
            String query = "SELECT product_name FROM product WHERE product_id = " + this.txtProduct_ID3.getText();
            ResultSet result = statement.executeQuery(query);
            while(result.next()){
                this.txtProduct_Name3.setText(result.getString("product_name"));
            }
            result.close();
            statement.close();
        }catch(SQLException error){
            JOptionPane.showMessageDialog(null, "Terjadi error: " + error);
        }
    }//GEN-LAST:event_txtProduct_ID3CaretUpdate

    private void buttonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKeluarActionPerformed
        int ex = JOptionPane.showConfirmDialog(null, "Apakah anda akan keluar?", "Anda yakin?", JOptionPane.YES_NO_OPTION);
        if(ex == 0){
            dispose();
        }
    }//GEN-LAST:event_buttonKeluarActionPerformed

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
        String txtPurchaseID = this.txtPurchase_ID.getText();
        String txtVendorID = this.txtVendor_ID.getText();
        String txtVendorRefNo = this.txtVendor_RefNo.getText();
        
        java.util.Date txtPurchaseDate = this.txtPurchase_Date.getDate();
        
        String txtProductID1 = this.txtProduct_ID1.getText();
        String txtProductID2 = this.txtProduct_ID2.getText();
        String txtProductID3 = this.txtProduct_ID3.getText();
        
        String txtPrice1 = this.txtPrice1.getText();
        String txtPrice2 = this.txtPrice2.getText();
        String txtPrice3 = this.txtPrice3.getText();
        
        String txtQty1 = this.txtQty1.getText();
        String txtQty2 = this.txtQty2.getText();
        String txtQty3 = this.txtQty3.getText();
        
        if(txtPurchase_ID.getText().equals("") || txtVendor_ID.getText().equals("") || txtVendor_RefNo.equals("") || txtPurchase_Date.getDate() == null){
            JOptionPane.showMessageDialog(this, "Tidak dapat menyimpan data karena ada kolom yang kosong. Silakan dicek kembali.");
        }else{
            try{
                Connection connection = Database.koneksiKeDatabase();
                String sql = "INSERT INTO purchase VALUES (?, ?, ?, ?)";
                PreparedStatement preparedStatement = connection.prepareStatement(sql);
                preparedStatement.setString(1, txtPurchaseID);
                preparedStatement.setDate(2, new java.sql.Date(txtPurchaseDate.getTime()));
                preparedStatement.setString(3, txtVendorID);
                preparedStatement.setString(4, txtVendorRefNo);
                preparedStatement.executeUpdate();
                preparedStatement.close();
                
                JOptionPane.showMessageDialog(this, "Berhasil memasukkan data ke tabel purchase!");
            }catch(SQLException error){
                JOptionPane.showMessageDialog(null, "Terjadi error: " + error);
            }
            
            if(txtProductID1.equals("") || txtQty1.equals("") || txtPrice1.equals("")){
                JOptionPane.showMessageDialog(null, "Kolom pengisian tidak boleh kosong");
            }else{
                try{
                    Connection connection = Database.koneksiKeDatabase();
                    String sql = "INSERT INTO purchase_detail VALUES (?, ?, ?, ?)";
                    PreparedStatement preparedStatement = connection.prepareStatement(sql);
                    preparedStatement.setString(1, txtProductID1);
                    preparedStatement.setString(2, txtQty1);
                    preparedStatement.setString(3, txtPrice1);
                    
                    preparedStatement.executeUpdate();
                    preparedStatement.close();
                }catch(SQLException error){
                    JOptionPane.showMessageDialog(null, "Terjadi error: " + error);
                }
            }
            
            if((txtProductID1.equals("") || txtQty1.equals("") || txtPrice1.equals("")) && (txtProductID2.equals("") || txtQty2.equals("") || txtPrice2.equals(""))){
                JOptionPane.showMessageDialog(null, "Kolom pengisian pada baris pengisian product tidak boleh kosong");
            }else{
                try{
                    Connection connection = Database.koneksiKeDatabase();
                    String sql = "INSERT INTO purchase_detail VALUES (?, ?, ?, ?), (?, ?, ?, ?)";
                    PreparedStatement preparedStatement = connection.prepareStatement(sql);
                    preparedStatement.setString(1, txtProductID1);
                    preparedStatement.setString(2, txtQty1);
                    preparedStatement.setString(3, txtPrice1);
                    
                    preparedStatement.setString(4, txtProductID2);
                    preparedStatement.setString(5, txtQty2);
                    preparedStatement.setString(6, txtPrice2);
                    
                    preparedStatement.executeUpdate();
                    preparedStatement.close();
                }catch(SQLException error){
                    JOptionPane.showMessageDialog(null, "Terjadi error: " + error);
                }
            }
            
            if((txtProductID1.equals("") || txtQty1.equals("") || txtPrice1.equals("")) && (txtProductID2.equals("") || txtQty2.equals("") || txtPrice2.equals("")) && (txtProductID3.equals("") || txtQty3.equals("") || txtPrice3.equals(""))){
                JOptionPane.showMessageDialog(null, "Kolom pengisian tidak boleh kosong");
            }else{
                try{
                    Connection connection = Database.koneksiKeDatabase();
                    String sql = "INSERT INTO purchase_detail VALUES (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?)";
                    PreparedStatement preparedStatement = connection.prepareStatement(sql);
                    preparedStatement.setString(1, txtProductID1);
                    preparedStatement.setString(2, txtQty1);
                    preparedStatement.setString(3, txtPrice1);
                    
                    preparedStatement.setString(4, txtProductID2);
                    preparedStatement.setString(5, txtQty2);
                    preparedStatement.setString(6, txtPrice2);
                    
                    preparedStatement.setString(7, txtProductID3);
                    preparedStatement.setString(8, txtQty3);
                    preparedStatement.setString(9, txtPrice3);
                    
                    preparedStatement.executeUpdate();
                    preparedStatement.close();
                }catch(SQLException error){
                    JOptionPane.showMessageDialog(null, "Terjadi error: " + error);
                }
            }
        }

    }//GEN-LAST:event_buttonSimpanActionPerformed

    private void txtQty1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtQty1CaretUpdate
        if(!txtPrice1.equals("")){
            int subTotal1 = Integer.parseInt(txtQty1.getText()) * Integer.parseInt(txtPrice1.getText());
            txtSubTotal1.setText(Integer.toString(subTotal1));
        }
    }//GEN-LAST:event_txtQty1CaretUpdate

    private void txtQty2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtQty2CaretUpdate
        if(!txtPrice2.equals("")){
            int subTotal2 = Integer.parseInt(txtQty2.getText()) * Integer.parseInt(txtPrice2.getText());
            txtSubTotal2.setText(Integer.toString(subTotal2));
        }
    }//GEN-LAST:event_txtQty2CaretUpdate

    private void txtQty3CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtQty3CaretUpdate
        if(!txtPrice3.equals("")){
            int subTotal3 = Integer.parseInt(txtQty3.getText()) * Integer.parseInt(txtPrice3.getText());
            txtSubTotal3.setText(Integer.toString(subTotal3));
        }
    }//GEN-LAST:event_txtQty3CaretUpdate

    private void txtPrice1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtPrice1CaretUpdate
        if(!txtQty1.equals("")){
            int subTotal1  = Integer.parseInt(txtQty1.getText()) * Integer.parseInt(txtPrice1.getText());
            txtSubTotal1.setText(Integer.toString(subTotal1));
        }
    }//GEN-LAST:event_txtPrice1CaretUpdate

    private void txtPrice2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtPrice2CaretUpdate
        if(!txtQty2.equals("")){
            int subTotal2  = Integer.parseInt(txtQty2.getText()) * Integer.parseInt(txtPrice2.getText());
            txtSubTotal2.setText(Integer.toString(subTotal2));
        }
    }//GEN-LAST:event_txtPrice2CaretUpdate

    private void txtPrice3CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtPrice3CaretUpdate
        // TODO add your handling code here:
        
        if(!txtQty3.equals("")){
            int subTotal3  = Integer.parseInt(txtQty3.getText()) * Integer.parseInt(txtPrice3.getText());
            txtSubTotal3.setText(Integer.toString(subTotal3));
        }
    }//GEN-LAST:event_txtPrice3CaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPurchase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonKeluar;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JButton buttonView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel txtGrandTotal;
    private javax.swing.JTextField txtPrice1;
    private javax.swing.JTextField txtPrice2;
    private javax.swing.JTextField txtPrice3;
    private javax.swing.JTextField txtProduct_ID1;
    private javax.swing.JTextField txtProduct_ID2;
    private javax.swing.JTextField txtProduct_ID3;
    private javax.swing.JTextField txtProduct_Name1;
    private javax.swing.JTextField txtProduct_Name2;
    private javax.swing.JTextField txtProduct_Name3;
    private com.toedter.calendar.JDateChooser txtPurchase_Date;
    private javax.swing.JTextField txtPurchase_ID;
    private javax.swing.JTextField txtQty1;
    private javax.swing.JTextField txtQty2;
    private javax.swing.JTextField txtQty3;
    private javax.swing.JTextField txtSubTotal1;
    private javax.swing.JTextField txtSubTotal2;
    private javax.swing.JTextField txtSubTotal3;
    private javax.swing.JTextField txtVendor_ID;
    private javax.swing.JTextField txtVendor_RefNo;
    private javax.swing.JTextField txtViewVendor_Name;
    // End of variables declaration//GEN-END:variables
}
